shamefullyHoist: true

overrides:
  "@rolldown/pluginutils": 1.0.0-beta.10

catalog:
  "@antfu/eslint-config": ^4.16.2
  "@iconify-json/devicon": ^1.2.29
  "@iconify-json/logos": ^1.2.4
  "@iconify-json/solar": ^1.2.2
  "@slidev/cli": ^52.0.0
  "@slidev/client": ^52.0.0
  "@slidev/theme-default": ^0.25.0
  "@types/seedrandom": ^3.0.8
  "@zinkawaii/eslint-config": ^0.3.0
  eslint: ^9.31.0
  playwright-chromium: ^1.54.1
  seedrandom: ^3.0.5
  vue: ^3.5.17

onlyBuiltDependencies:
  - esbuild
  - playwright-chromium
